global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "rules/alert-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # - job_name: 'next-japan-app'
  #   static_configs:
  #     - targets: ['next-japan-app:3030']
  #   metrics_path: '/api/metrics'
  #   scrape_interval: 10s

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s 